// Suflor.me — arayüz metinlerinin İngilizcesi (tek kaynak). Anahtar Türkçe metnin kendisi; L("…") Türkçe arayüzde metni olduğu
// gibi, İngilizcede buradaki karşılığını gösterir. Yükleyenler: eklenti (manifest içerik betiği, background.js importScripts,
// popup.html) ve aktarıcı (pano.html / hazirlik.html'e gömer). Kurulum sihirbazı kendi anahtarlı sözlüğünü kullanır (ortak metin 2).
// Kural: pano = "panel", mini pano = "mini panel" ("dashboard"/"board" yok); yeni metin eklenince test/dil.py koştur.
globalThis.SUFLOR_EN = {
  // --- birden çok yüzeyde
  "Türkçe": "Turkish",
  "İngilizce": "English",
  "Gönder": "Send",
  "Son 1 dk": "Last 1 min",
  "Kanıt": "Evidence",
  "Söyle": "Say",
  "Dur": "Stop",
  "Cevap": "Answer",
  "Not": "Note",
  "⭐ Önemli an: şu anı özette öne çıkar": "⭐ Key moment: highlight this moment in the summary",
  "Son 1 dk özeti hazırlanıyor…": "Preparing the last-minute summary…",
  "Claude'a soruldu: ": "Asked Claude: ",
  "Yaptım": "Done",
  "{n} dk kaldı": "{n} min left",
  "süre doldu": "time's up",
  " · {n} madde geride": " · {n} items behind",
  "not": "note",
  "soru": "question",
  "gönderilemedi": "not sent",
  "Claude son 1 dakikayı özetlesin": "Claude sums up the last minute",
  "Toplantı ekranını kanıt olarak kaydet; kutudaki yazı not olur": "Save the meeting screen as evidence; text in the box becomes its note",
  "henüz satır yok": "no lines yet",
  "son satır {a} önce · {k}": "last line {a} ago · {k}",
  "{n} sn": "{n} s",
  "{n} dk": "{n} min",
  "Döküm dili yanlış": "Transcript language is wrong",
  "Satır gelmiyor": "No lines coming in",
  "Sistem Ayarları → Gizlilik ve Güvenlik → Ekran ve Sistem Sesi Kaydı → Suflor Ses": "System Settings → Privacy & Security → Screen & System Audio Recording → Suflor Ses",
  "Senin sesin yazılmıyor": "Your voice isn't being transcribed",
  "mikrofon açılamadı — toplantı sekmesini yenile": "couldn't open the microphone — reload the meeting tab",
  "mikrofon açık ama ses gelmiyor": "microphone is on but no audio is coming in",
  "Claude izlemiyor — kart gelmez": "Claude isn't watching — no cards will come",
  "Dinliyorum": "Listening",
  "Claude hazır — toplantı bekleniyor": "Claude is ready — waiting for a meeting",
  "Hazır — toplantı bekleniyor": "Ready — waiting for a meeting",
  "Not ya da soru (başa ?)": "Note or question (start with ?)",
  "bağlam": "context",
  "Dokun: kapat": "Tap to close",
  "Gerek yok — Claude bir daha önermesin": "Not needed — Claude won't suggest it again",
  "bilinmiyor": "unknown",
  "Panoyu aç": "Open panel",
  // --- pano ve mini pano
  "toplantı bekleniyor": "waiting for a meeting",
  "Mini pano: her zaman üstte duran küçük pencere": "Mini panel: a small window that stays on top",
  "Döküm": "Transcript",
  "↓ Canlıya dön": "↓ Back to live",
  "Sürükleyerek genişlet/daralt · çift tıkla: varsayılan": "Drag to resize · double-click: default",
  "Takvimde olmayan bir toplantı için": "For a meeting that isn't in your calendar",
  "Takvimi yenile": "Refresh calendar",
  "Kişi — konu (ör. Ayşe — bütçe)": "Person — topic (e.g. Anna — budget)",
  "Toplantı bağlantısı (isteğe bağlı; yoksa Teams açılır)": "Meeting link (optional; Teams opens if empty)",
  "Yürütücü (ben yönetiyorum)": "Lead (I'm running it)",
  "Katılımcı": "Participant",
  "Dinleyici": "Listener",
  "Karışık": "Mixed",
  "Başlat": "Start",
  "Vazgeç": "Cancel",
  "Şimdi": "Now",
  "Gündem": "Agenda",
  "Açık sorular": "Open questions",
  "Kanıtlar": "Evidence",
  "Hassas ifade": "Sensitive phrase",
  "değer dosyaya yazılmaz": "value is never written to file",
  "Konuşmada şifre, parola, token, API anahtarı gibi bir kelime geçti. Değerin kendisi dosyaya yazılmaz; yalnız uyarı konur.": "A word like password, token or API key came up. The value itself is never written to file; only a marker is.",
  "aç": "open",
  "Toplantı başlayınca konuşma burada akar.": "Once the meeting starts, the conversation flows here.",
  "Taslak ({d}); kesin metin gelince yerine geçer": "Draft ({d}); replaced when the final text arrives",
  "Whisper bekleniyor": "waiting for Whisper",
  "konuşuluyor": "in progress",
  "taslak": "draft",
  "gizli": "private",
  "olumlu": "positive",
  "nötr": "neutral",
  "gergin": "tense",
  "olumsuz": "negative",
  "ilgili": "engaged",
  "heyecanlı": "excited",
  "tedirgin": "uneasy",
  "savunmada": "defensive",
  "ilgisiz": "disengaged",
  "kararsız": "undecided",
  "ton": "tone",
  "Claude tahmini, {t}": "Claude's estimate, {t}",
  "tahmin": "estimate",
  "Şimdilik kart yok. Claude toplantıyı izlerken öneriler buraya düşer.": "No cards yet. While Claude follows the meeting, suggestions land here.",
  "Gerek yok": "Not needed",
  "{n} dk aşıldı": "{n} min over",
  "bitiş {t}": "ends {t}",
  " · gündem {a}/{b}": " · agenda {a}/{b}",
  " (beklenen {n})": " (expected {n})",
  "Konuşma payı ölçülemiyor (konuşmacı adı gelmiyor)": "Talk share can't be measured (no speaker names)",
  "Konuşma payı": "Talk share",
  " (son 10 dk)": " (last 10 min)",
  "toplam": "total",
  "gündem {a}/{b}": "agenda {a}/{b}",
  "Takvim izni yok — Sistem Ayarları → Gizlilik ve Güvenlik → Takvimler → Suflor Takvim.": "No calendar access — System Settings → Privacy & Security → Calendars → Suflor Takvim.",
  "takvim okunuyor…": "reading calendar…",
  "şimdi": "now",
  "{n} dk sonra": "in {n} min",
  "düzenleyen sen": "you're the organizer",
  "takvim yenileniyor…": "refreshing calendar…",
  "Kişi ve konuyu yaz": "Enter the person and topic",
  "başlatılıyor…": "starting…",
  "başlatılamadı": "couldn't start",
  "Toplantı": "Meeting",
  "yürütücü": "lead",
  "katılımcı": "participant",
  "dinleyici": "listener",
  "Claude tahmini: şu an bu madde konuşuluyor": "Claude's estimate: this item is being discussed now",
  "Toplantı başlayınca gündem burada görünür.": "The agenda appears here once the meeting starts.",
  "Gündem yok": "No agenda",
  "Mini pano": "Mini panel",
  "Güncelleniyor…": "Updating…",
  "Güncelleme başarısız — yeniden dene": "Update failed — try again",
  "Geri bildirim gönder": "Send feedback",
  "Geri bildirim": "Feedback",
  "Aksayan, eksik ya da beğendiğin bir şey varsa yaz; geliştiriciye gider. Yazdığın metin olduğu gibi gider: kişi adı, şifre ya da toplantı içeriği yazma.": "Tell us what broke, what's missing or what you liked; it goes to the developer. Your text is sent as written: don't include names, passwords or meeting content.",
  "Ne oldu? Ne bekliyordun?": "What happened? What did you expect?",
  "Teknik bilgiyi ekle (sürümler, Mac, son olaylar — toplantı içeriği yok)": "Include technical info (versions, Mac, recent events — no meeting content)",
  "Önce ne olduğunu yaz": "Describe what happened first",
  "gönderiliyor…": "sending…",
  "Teşekkürler — gönderildi": "Thanks — sent",
  "Gönderilemedi — sonra yeniden denenecek": "Couldn't send — will retry later",
  "Elle başlat": "Start manually",
  "Suflor.me güncellendi": "Suflor.me was updated",
  "açık bir toplantı sekmesi varsa yenile": "reload any open meeting tab",
  "Diğer → Dil ve konuşma → Canlı altyazı": "More → Language and speech → Live captions",
  "altyazıyı aç: ": "turn on captions: ",
  "Karşı tarafın sesi için izin gerekiyor": "Permission needed for the other side's audio",
  "Karşı tarafın sesi yazılmıyor": "The other side isn't being transcribed",
  "Suflor.me simgesi → Karşı taraf → Aç": "Suflor.me icon → Other side → Open",
  "Toplantı sekmesinden sinyal gelmiyor": "No signal from the meeting tab",
  "sekmeyi yenile": "reload the tab",
  "Toplantıdasın": "In a meeting",
  "bağlanıyor…": "connecting…",
  "Mini pano açılamadı": "Couldn't open the mini panel",
  "açılır pencereye izin ver": "allow pop-ups",
  "Takvim bağlı değil — toplantıyı elle başlatabilirsin.": "Calendar isn't connected — you can start a meeting manually.",
  "Sıradaki": "Up next",
  "Bugün": "Today",
  "Takvimde toplantı yok": "No meetings in your calendar",
  "Toplantı başlat": "Start a meeting",
  "Pano eski — sayfayı yenileyip tekrar dene": "The panel is out of date — reload the page and try again",
  "Başladı — hazır olunca toplantıya geçilir": "Started — moves to the meeting when ready",
  "Başladı — Claude gündemi kurup izlemeye başlar": "Started — Claude sets the agenda and starts watching",
  "Suflor.me'ye ulaşılamadı": "Couldn't reach Suflor.me",
  "Suflor.me'ye ulaşılamıyor": "Can't reach Suflor.me",
  "birkaç saniye içinde yeniden denenir": "retrying in a few seconds",
  "Güncelle": "Update",
  "Yeni sürüm hazır": "A new version is ready",
  "Onayla — birkaç saniye kesilir": "Confirm — pauses for a few seconds",
  "Güncellenemedi": "Couldn't update",
  "önceki toplantınınki gizli": "previous meeting's is hidden",
  "Bağlam": "Context",
  "Claude okur": "Claude reads",
  "kutu": "box",
  "bırakıldı": "dropped",
  "Dosya çok büyük": "File too large",
  "en çok 25 MB": "25 MB at most",
  "Bağlam eklendi — Claude okuyacak": "Context added — Claude will read it",
  "Bağlam eklenemedi": "Couldn't add context",
  "Bağlam (isteğe bağlı): bağlantı ya da dosya yolu, her satıra bir — dosyayı panoya da bırakabilirsin": "Context (optional): link or file path, one per line — you can also drop a file on the panel",
  "Claude'un okuduğu bağlantı ve belgeler. Dosyayı panoya bırak ya da kutuya bağlantı/dosya yolu yaz.": "Links and documents Claude reads. Drop a file on the panel or type a link/file path in the box.",
  "Başta ? varsa Claude'a soru, yoksa not. ⌘Enter: her zaman soru.": "Starting with ? asks Claude, otherwise it's a note. ⌘Enter: always a question.",
  "Suflor.me olmadan katıl": "Join without Suflor.me",
  "son satır {t}": "last line {t}",
  "davet notu okunuyor…": "reading the invite…",
  "davet notundan": "from the invite",
  "Son toplantılar": "Recent meetings",
  "Brifing": "Briefing",
  "Dikkat": "Watch for",
  "Açık kalanlar": "Still open",
  "Geçmişte": "Previously",
  "Yeniden hazırla": "Prepare again",
  "Claude brifingi hazırlıyor… (1–2 dk)": "Claude is preparing the briefing… (1–2 min)",
  "Claude geçmiş görüşmelere, açık sorulara ve belgelere bakıp kısa bir brifing hazırlar.": "Claude looks at past meetings, open questions and documents and prepares a short briefing.",
  "Yeniden dene": "Try again",
  "Brifing hazırla": "Prepare briefing",
  "Brifing başlatılamadı": "Couldn't start the briefing",
  "Özeti aç": "Open summary",
  "Öneri": "Suggestion",
  "Dün": "Yesterday",
  "Özet açılamadı": "Couldn't open the summary",
  // --- hazırlık sayfası
  "Suflor.me hazırlanıyor": "Suflor.me is getting ready",
  "Hemen katıl": "Join now",
  "Katılma": "Don't join",
  "Toplantıya geçilmeyecek; bu sekmeyi kapatabilirsin.": "You won't be taken to the meeting; you can close this tab.",
  "Claude oturumu açıldı (Terminal)": "Claude session opened (Terminal)",
  "Gündem hazırlandı": "Agenda ready",
  "Konuşma tanıma hazır": "Speech recognition ready",
  "Claude izliyor": "Claude is watching",
  "Takvimde toplantı bağlantısı yok — toplantıya kendin katıl.": "No meeting link in the calendar — join the meeting yourself.",
  "Bağlantı yok — Teams açılacak; toplantını oradan seç.": "No link — Teams will open; pick your meeting there.",
  "Hazır — toplantıya geçiliyor…": "Ready — taking you to the meeting…",
  "En geç {n} dk içinde toplantıya geçilecek": "You'll be taken to the meeting within {n} min at the latest",
  // --- Teams sayfası (şerit, tost, kart penceresi)
  "Suflor.me: canlı altyazı açıldı": "Suflor.me: live captions turned on",
  "Suflor.me: altyazı konuşma dili {d} yapıldı (gündem dili)": "Suflor.me: caption spoken language set to {d} (agenda language)",
  "Suflor.me: altyazıyı açamadım — bir kez elle aç ({y}), yolu öğrenirim": "Suflor.me: couldn't turn on captions — turn them on once by hand ({y}) and I'll learn the way",
  "📷 Kanıt {n} kaydedildi": "📷 Evidence {n} saved",
  "📷 Kanıt kaydedilemedi: ": "📷 Couldn't save evidence: ",
  "+{n} dk": "+{n} min",
  "Çalışma alanını seç: Suflor.me simgesi": "Pick a workspace: Suflor.me icon",
  "Bu Chrome \"{a}\" alanına yazıyor": "This Chrome writes to \"{a}\"",
  "Ad için altyazıyı aç: {y}": "Turn on captions for names: {y}",
  "Altyazı kapalı: {y}": "Captions are off: {y}",
  "Karşı tarafın sesi için: simge → Karşı taraf → Aç": "Other side's audio: icon → Other side → Open",
  "Döküm dili yanlış — panoya bak": "Transcript language is wrong — see the panel",
  "Şimdilik kart yok": "No cards yet",
  "Suflor.me — kartlar için tıkla": "Suflor.me — click for cards",
  // --- eklenti penceresi
  "Bu Chrome'un yazdığı çalışma alanı": "The workspace this Chrome writes to",
  "Bu Chrome hangi çalışma alanına yazsın?": "Which workspace should this Chrome write to?",
  "Bu Mac'te birden fazla Suflor.me aktarıcısı çalışıyor. Bir kez seç; Ayarlar'dan değiştirebilirsin.": "More than one Suflor.me relay is running on this Mac. Pick one once; you can change it in Settings.",
  "bakılıyor…": "checking…",
  "Ayarlar": "Settings",
  "Sesi Mac'te yazıya çevir": "Transcribe audio on this Mac",
  "Çalışma alanı": "Workspace",
  "Suflor.me kapalı": "Suflor.me is off",
  "kurulum klasöründe aktarici-kur'a çift tıkla": "double-click aktarici-kur in the install folder",
  "{n} satır bekliyor; Suflor.me açılınca gönderilir.": "{n} lines waiting; they'll be sent once Suflor.me is up.",
  "altyazıyı aç": "turn on captions",
  "Altyazıyı aç: ": "Turn on captions: ",
  "Karşı taraf: izin gerekiyor": "Other side: permission needed",
  "Karşı taraf: ses yazılmıyor": "Other side: not being transcribed",
  "Aç": "Open",
  "istendi…": "requested…",
  "Panodan başlat": "Start it from the panel",
  "1 açık kart": "1 open card",
  "{n} açık kart": "{n} open cards",
  // --- eklenti arka planı (bildirimler)
  "⭐ işaretlenemedi: ": "⭐ couldn't be marked: ",
  "Özet istenemedi: ": "Couldn't request a summary: ",
  "aktarıcıya ulaşılamadı (127.0.0.1:8765)": "can't reach the relay (127.0.0.1:8765)",
  "Açık toplantı sekmesi yok (Teams).": "No open meeting tab (Teams).",
  "Çalışma alanı seçilmedi — Suflor.me simgesine tıklayıp seç.": "No workspace selected — click the Suflor.me icon and pick one.",
  "🎙 Karşı tarafın sesi zaten yazılıyor": "🎙 The other side's audio is already being transcribed",
  "Toplantı sekmesini öne getirdim — karşı tarafın sesi için Suflor.me simgesi → Karşı taraf → Aç'a bir kez daha bas": "I brought the meeting tab to the front — for the other side's audio, click Suflor.me icon → Other side → Open once more",
  "🎙 Whisper: karşı tarafın sesi de yazılıyor": "🎙 Whisper: the other side's audio is now being transcribed too",
  "Whisper karşı taraf açılamadı: ": "Couldn't start Whisper for the other side: ",
  "Suflor.me — kanıt kaydedilemedi": "Suflor.me — couldn't save evidence",
  "Toplantı penceresi simge durumunda — pencereyi açıp tekrar dene.": "The meeting window is minimised — restore it and try again.",
  "Aktarıcıya ulaşılamadı (çalışma alanının aktarıcısı kapalı).": "Can't reach the relay (this workspace's relay is off).",
  "{n} dk sonra başlıyor": "Starts in {n} min",
  "Başlıyor": "Starting",
  ". Suflor.me'yi başlatayım mı?": ". Start Suflor.me?",
  "Suflor.me'yi başlat": "Start Suflor.me",
  "Suflor.me başlatılamadı": "Couldn't start Suflor.me",
  // --- v0.14.0 yerel anahtar ve onay kartı (#76)
  "Onay bekliyor": "Needs your approval",
  "Onayla": "Approve",
  "Reddet": "Decline",
  "Pano anahtarsız açıldı": "Panel opened without its key",
  "Suflor.me simgesine tıkla → Panoyu aç": "Click the Suflor.me icon → Open panel",
  "Anahtar yok — panoyu Suflor.me simgesinden aç, sonra bu sayfayı yenile.": "No key — open the panel from the Suflor.me icon, then reload this page.",
  "Anahtarsız yerel istek geldi": "A local request arrived without the key",
  "Eklenti eski sürümde": "Extension is out of date",
  "toplantı yardımcısı eski olabilir — aktarici-kur ile yeniden kur": "the meeting helper may be outdated — reinstall with aktarici-kur",
  "chrome://extensions → Suflor.me → ↻ yenile": "chrome://extensions → Suflor.me → ↻ reload",
  "Önemli güncelleme": "Important update",
  "Güvenlik ya da kurulum düzeltmesi — toplantı yokken güncelle": "Security or setup fix — update when you're not in a meeting"
};
